# Generated by Django 4.1.5 on 2023-01-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_departement_postes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse_email',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='genre',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nombre_d_enfants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employe',
            name='numero_d_employe',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='numero_tel',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='responsable_hierarchique',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='postes',
            name='Niveau_hiérarchique',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='postes',
            name='Nom',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
