# Generated by Django 4.1.5 on 2023-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_departement_nom_alter_employe_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
