# Generated by Django 4.1.5 on 2023-01-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_departement_id_alter_employe_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='responsable_hierarchique',
        ),
        migrations.AlterField(
            model_name='departement',
            name='responsable_departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.employe'),
        ),
        migrations.AlterField(
            model_name='postes',
            name='Département_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.departement'),
        ),
    ]
