# Generated by Django 4.1.5 on 2023-01-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_employe_responsable_hierarchique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='poste_id',
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='type_contract',
            field=models.CharField(default='CDD', max_length=100),
        ),
    ]
