# Generated by Django 4.1.5 on 2023-01-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_employe_poste_id_employe_poste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='departement_id',
        ),
        migrations.AlterField(
            model_name='employe',
            name='genre',
            field=models.CharField(choices=[('OPTION_1', 'Homme'), ('OPTION_2', 'Femme'), ('OPTION_3', 'Autre')], default='NONE', max_length=100),
        ),
    ]
